source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIViewController-InputView_Example', :exclusive => true do
  pod "UIViewController-InputView", :path => "../"
end

target 'UIViewController-InputView_Tests', :exclusive => true do
  pod "UIViewController-InputView", :path => "../"

  
end
